### ISSUE TITLE
 [BUG] Installer Script and Operation Not Permitted Error

### ISSUE THREAD

**Issue by ernivani** [bhumit070/deps-cleaner#1]
**Describe the bug**  
1. **Installer script does not auto-source**  
   After running:
   ```bash
   curl https://raw.githubusercontent.com/bhumit070/deps-cleaner/main/install.sh | bash
   ```
   The `.bashrc` (or `.zshrc`) is updated with the `PATH` export, but the changes aren’t sourced automatically. This requires the user to manually run `source ~/.bashrc` or open a new terminal before `deps-cleaner` is recognized as a command.

2. **Operation not permitted when cleaning from `~`**  
   On macOS (M1 or Intel), running the command from the home directory:
   ```bash
   deps-cleaner clean
   ```
   results in:
   ```
   Are you sure, you want to remove dependencies in this folder - /Users/<username> (y/N): y
   open /Users/<username>/.Trash: operation not permitted
   ```
   It appears that removing items to the `~/.Trash` folder can sometimes fail due to macOS permissions.

**To Reproduce**  
1. Install using the provided `curl ... | bash` command on macOS or Linux.
2. Attempt to run `deps-cleaner` in the same terminal session (without manually sourcing your shell file).
3. On macOS, from the home directory, run `deps-cleaner clean` and confirm the removal prompt with `y`.

**Expected behavior**  
- **Installer**: Ideally, the script should automatically source the correct shell profile or prompt the user to do so, ensuring `deps-cleaner` is available immediately after installation.  
- **Home Directory Clean**: Either it should skip restricted system folders (like `~/.Trash`) or use a different mechanism for deletion (with clear user instructions).

**Environment (please complete the following information):**
- **OS**: [e.g. macOS 13.0 Ventura, Ubuntu 22.04]  
- **Shell**: [e.g. zsh, bash]  
- **Deps Cleaner Version**: [e.g. 0.0.7]  
- **Installation Method**: [e.g. `curl ... | bash`, manual build]

**Comment by bhumit070** [comment]
Hello @ernivani  I have published all your concerned issues in v0.0.3 release, thanks for reporting the issues and making this tool better.

Please open new PR if you find any more issue, or you think we can add new feature to polish this tool.
