### ISSUE TITLE
[FEATURE REQUEST] Show Storage Saved

### ISSUE THREAD

**Issue by ernivani** [bhumit070/deps-cleaner#2]
It would be helpful to see how much disk space was freed after deleting each dependency folder. Currently, `deps-cleaner` does not provide any size metrics.

**Describe the solution you’d like**  
- After each deletion or at the end of the run, print a summary of the total size of deleted files/folders.  
- Optionally display this in a more human-readable format (e.g., `1.2 GB freed`).

**Describe alternatives you’ve considered**  
- Manually checking disk space before and after using system tools like `du -sh`. However, having it built into `deps-cleaner` provides immediate feedback.

**Comment by parnexcodes** [comment]
Hi @bhumit070 I can work on this if it's possible.

**Comment by bhumit070** [comment]
@parnexcodes yes please go ahead.

**Comment by bhumit070** [comment]
Closing as it is added in v0.0.2
